# Generated by Django 5.0.7 on 2024-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.IntegerField()),
                ('names', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=9)),
                ('age', models.IntegerField()),
                ('patientssituation', models.TextField()),
                ('healthissues', models.CharField(max_length=10)),
                ('dateregistered', models.DateField()),
            ],
        ),
    ]
