# Generated by Django 5.0.7 on 2024-08-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regpatientsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patientid',
        ),
    ]
